dist: xenial
sudo: required
language: python
branches:
  only:
    - master
    - /^dev(-.+)?$/
matrix:
  include:
  - name: "Test with Python 3.5"
    python: "3.5"
    env: PATH_PYTHON=/home/travis/virtualenv/python3.5/bin/python
  - name: "Test with Python 3.7"
    python: "3.7"
    env: PATH_PYTHON=/home/travis/virtualenv/python3.7/bin/python
services:
  - mysql
addons:
  apt:
    update: true
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - sudo make setup_tarvisci
script:
  - sudo make do_test
